Single Window Integration Changes for SSO
eNagarsewaU/DIGIT-UKD pull request #51
Opened 2023-02-14 05:57 UTC by codes1024

this changes is regarding the single sign on.

2023-02-14 09:29 UTC, vinothrallapalli-eGov approved these changes

2023-02-14 10:19 UTC, vinothrallapalli-eGov requested changes

2023-02-14 10:19 UTC, vinothrallapalli-eGov commented on core-services/zuul/src/main/resources/routes.properties
> +zuul.routes.tl-services.url=/v1/external/_create
this change is not required. Remove changes in this file

2023-02-15 05:40 UTC, codes1024 commented
Please check i have removed this code from the route.properties

2023-02-15 05:56 UTC, codes1024 commented on core-services/zuul/src/main/resources/routes.properties
> +zuul.routes.tl-services.url=/v1/external/_create
Sir, i have done this changes.

2023-02-15 06:00 UTC, vinothrallapalli-eGov requested changes

2023-02-15 06:00 UTC, vinothrallapalli-eGov commented on core-services/zuul/src/main/resources/application.properties
> +SSO_ENDPOINT=/tl-services/v1/external/_create
remove this

2023-02-15 06:00 UTC, vinothrallapalli-eGov commented on core-services/zuul/src/main/resources/routes.properties
> +zuul.routes.tl-services.url=http://localhost:8079/
revert this change

2023-02-15 06:14 UTC, codes1024 commented on core-services/zuul/src/main/resources/routes.properties
> +zuul.routes.tl-services.url=http://localhost:8079/
done sir

2023-02-15 06:20 UTC, vinothrallapalli-eGov approved these changes

2023-02-15 06:20 UTC, merged