Enhancement done to support tenant wise and date range push data.
eNagarsewaU/DIGIT-UKD pull request #53
Opened 2023-02-22 06:27 UTC by manastanmay-eGov

Enhancement done in Tl service, Collection Service and Property Services

2023-03-10 06:51 UTC, vinothrallapalli-eGov requested changes

2023-03-10 06:51 UTC, vinothrallapalli-eGov commented on business-services/collection-services/src/main/java/org/egov/collection/repository/PaymentRepository.java
> +        if(paymentSearchCriteria.getTenantId() != null && !paymentSearchCriteria.getTenantId().equals("uk")) {
Why the tenant id (UK) is hard-coded?

2023-03-10 06:51 UTC, vinothrallapalli-eGov commented on municipal-services/tl-services/src/main/java/org/egov/tl/repository/TLRepository.java
> +            System.out.println(criteria.getTenantId());
Remove sysout

2023-03-12 14:54 UTC, manastanmay-eGov commented on business-services/collection-services/src/main/java/org/egov/collection/repository/PaymentRepository.java
> +        if(paymentSearchCriteria.getTenantId() != null && !paymentSearchCriteria.getTenantId().equals("uk")) {
As this repo abd branch is  dedicated to UKD so have specified it as is . But if required then can make this code base generic as well. 
But i have referred Punjab code changes for the same and in there the state pb is hard coded.(https://github.com/egovernments/business-services/commit/73f419c7e5a63afb58fa43a67a54267a330e4819)

2023-03-12 14:54 UTC, manastanmay-eGov commented on municipal-services/tl-services/src/main/java/org/egov/tl/repository/TLRepository.java
> +            System.out.println(criteria.getTenantId());
Removed

2023-03-13 05:30 UTC, vinothrallapalli-eGov approved these changes

2023-03-13 05:30 UTC, merged